#include "bsp_buttons.h"

#include "ti_msp_dl_config.h"

void BSP_Buttons_Init(void)
{
    /* Pin mux, pull-ups, and input direction are generated by SysConfig. */
}

uint8_t BSP_Buttons_ReadPressedMask(void)
{
    uint32_t input_a = DL_GPIO_readPins(GPIO_BUTTONS_A_PORT,
        GPIO_BUTTONS_A_BUTTON_KEY3_PIN |
        GPIO_BUTTONS_A_BUTTON_KEY4_PIN);
    uint32_t input_b = DL_GPIO_readPins(GPIO_BUTTONS_B_PORT,
        GPIO_BUTTONS_B_BUTTON_KEY1_PIN |
        GPIO_BUTTONS_B_BUTTON_KEY2_PIN |
        GPIO_BUTTONS_B_BUTTON_KEY5_PIN);
    uint8_t pressed = 0U;

    if ((input_b & GPIO_BUTTONS_B_BUTTON_KEY1_PIN) == 0U) {
        pressed |= BSP_BUTTON_MASK(BSP_BUTTON_KEY1);
    }
    if ((input_b & GPIO_BUTTONS_B_BUTTON_KEY2_PIN) == 0U) {
        pressed |= BSP_BUTTON_MASK(BSP_BUTTON_KEY2);
    }
    if ((input_a & GPIO_BUTTONS_A_BUTTON_KEY3_PIN) == 0U) {
        pressed |= BSP_BUTTON_MASK(BSP_BUTTON_KEY3);
    }
    if ((input_a & GPIO_BUTTONS_A_BUTTON_KEY4_PIN) == 0U) {
        pressed |= BSP_BUTTON_MASK(BSP_BUTTON_KEY4);
    }
    if ((input_b & GPIO_BUTTONS_B_BUTTON_KEY5_PIN) == 0U) {
        pressed |= BSP_BUTTON_MASK(BSP_BUTTON_KEY5);
    }
    return pressed;
}

bool BSP_Buttons_IsPressed(bsp_button_t button)
{
    if ((uint8_t) button >= (uint8_t) BSP_BUTTON_COUNT) {
        return false;
    }
    return (BSP_Buttons_ReadPressedMask() & BSP_BUTTON_MASK(button)) != 0U;
}
